# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'instance_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_createInstance(object):
    def setupUi(self, createInstance):
        createInstance.setObjectName("createInstance")
        createInstance.resize(221, 122)
        self.buttonBox = QtWidgets.QDialogButtonBox(createInstance)
        self.buttonBox.setGeometry(QtCore.QRect(-140, 70, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(createInstance)
        self.label.setGeometry(QtCore.QRect(10, 10, 161, 17))
        self.label.setObjectName("label")
        self.comboBox = QtWidgets.QComboBox(createInstance)
        self.comboBox.setGeometry(QtCore.QRect(10, 30, 201, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(createInstance)
        self.buttonBox.accepted.connect(createInstance.accept) # type: ignore
        self.buttonBox.rejected.connect(createInstance.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(createInstance)

    def retranslateUi(self, createInstance):
        _translate = QtCore.QCoreApplication.translate
        createInstance.setWindowTitle(_translate("createInstance", "create instance"))
        self.label.setText(_translate("createInstance", "Selcect class"))
        self.comboBox.setItemText(0, _translate("createInstance", "eutardigrada black"))
        self.comboBox.setItemText(1, _translate("createInstance", "eutardigrada translucent"))
        self.comboBox.setItemText(2, _translate("createInstance", "heterotardigrada echiniscus"))
        self.comboBox.setItemText(3, _translate("createInstance", "scale"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    createInstance = QtWidgets.QDialog()
    ui = Ui_createInstance()
    ui.setupUi(createInstance)
    createInstance.show()
    sys.exit(app.exec_())
