version: "3"

services:
  x-common-processing: &common-processing
    image: tardigrada:latest
    build: .
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/tarmass
    stdin_open: true
    tty: true
    network_mode: "host"
    ipc: host
    environment:
      DISPLAY: $DISPLAY

  processing-cpu:
    <<: *common-processing
    profiles: [cpu]

  processing-gpu:
    <<: *common-processing
    profiles: [gpu]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: 1